name: transcendence

services:
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8090:8090"
    depends_on:
      - postgres_db
    networks:
      - transcendence_net
  postgres_db:
    build:                                
      context: ./postgres_setup           
      dockerfile: Dockerfile              
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - transcendence_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 3s
      timeout: 5s
      retries: 10

  redis_broker:
    image: redis:7-alpine
    container_name: redis_broker
    restart: unless-stopped
    # ports:
    #  - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - transcendence_net

  django_backend:
    build:
      context: ./django_backend
      dockerfile: Dockerfile
    container_name: django_backend
    restart: on-failure
    env_file:
      - .env
    environment:
      - HOST_IP=${HOST_IP}
    volumes:
      # Syncs your live code edits to the container so you don't have to rebuild! It's bind mount! (.)
      # bind mount is used for local development so live edits are sync immediately
      - ./django_backend:/app
      - media_data:/app/media  # for avatars uploaded from disk
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_broker:
        condition: service_started
    networks:
      - transcendence_net

  fastapi_backend:
    build:
      context: ./fastapi_backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    restart: on-failure
    env_file:
      - .env
    environment:
      - HOST_IP=${HOST_IP}
    volumes:
      - ./fastapi_backend:/app
    ports:
      - "8001:8001"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis_broker:
        condition: service_started
    networks:
      - transcendence_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # target: development
      target: production    #  Docker skips the dev server and builds Nginx
      args:
        HOST_IP: ${HOST_IP:-127.0.0.1}
    container_name: react_frontend
    restart: on-failure
    env_file:
      - ./frontend/.env
    ports:   # ---- WHEN WE ARE READY FOR PRODUCTION
      - "8080:80"
      - "8443:443"
    # ports: development
      # - "3000:3000"
    # volumes:
      # Bind mount for Hot Reloading -- removed on Nginx - Nginx loads baked-in static files
      # - ./frontend:/app
      # Anonymous volume to prevent local node_modules from saving other system's binary files and breaking the Linux container
      # - /app/node_modules

    # volumes:
    #   - ./certs/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
    #   - ./certs/privkey.pem:/etc/nginx/ssl/privkey.pem:ro

    depends_on:
      django_backend:
        condition: service_started
    networks:
      - transcendence_net

networks:
  transcendence_net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  media_data:


#for evaluation (production) it nginx will have to be setup to sent static files to nginx server and view and throw node.js away