from __future__ import annotations

from datetime import datetime
from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, TypeAdapter


# Maximum number of characters allowed in one chat message
CHAT_MESSAGE_MAX_LENGTH = 500

# Defensive maximum size for the access token sent by the client
ACCESS_TOKEN_MAX_LENGTH = 4096

# Maximum username length used by the Django user model
USERNAME_MAX_LENGTH = 150

# Maximum length of a safe error message returned to the frontend
ERROR_MESSAGE_MAX_LENGTH = 200


class ClientEventModel(BaseModel):
    """Base validation rules for every event received from the client"""

    model_config = ConfigDict(
        # Reject fields that are not explicitly declared in the model
        # This prevents clients from sending user_id username role or timestamp
        extra="forbid",

        # Reject values with incorrect types instead of converting them automatically
        # For example integer 123 must not be accepted as string "123"
        strict=True,

        # Remove whitespace from the beginning and end of string values
        # A string containing only spaces becomes empty and fails validation
        str_strip_whitespace=True,
    )


class AuthenticateClientEvent(ClientEventModel):
    """Authentication event sent immediately after opening the WebSocket"""

    # The event type must contain exactly this value
    type: Literal["authenticate"]

    # This commit validates only the structure and size of the token
    # JWT signature and expiration will be checked in the authentication commit
    access_token: str = Field(
        min_length=1,
        max_length=ACCESS_TOKEN_MAX_LENGTH,
    )


class SendMessageClientEvent(ClientEventModel):
    """Text message submitted by an authenticated chat client"""

    # The basic chat supports only one message sending event
    type: Literal["chat_message"]

    # The client controls only the message text
    # The backend will assign the author timestamp and message identifier
    text: str = Field(
        min_length=1,
        max_length=CHAT_MESSAGE_MAX_LENGTH,
    )


# This union contains every event accepted from the client
# Pydantic selects the correct model using the value of the type field
ClientEvent = Annotated[
    AuthenticateClientEvent | SendMessageClientEvent,
    Field(discriminator="type"),
]


# TypeAdapter validates the complete ClientEvent union
# This avoids manual dictionary checks in the future WebSocket endpoint
_CLIENT_EVENT_ADAPTER = TypeAdapter(ClientEvent)


def parse_client_event(payload: object) -> ClientEvent:
    """Validate decoded JSON as one of the supported client events"""

    # The function returns a concrete validated Pydantic model
    # Invalid input raises pydantic.ValidationError
    return _CLIENT_EVENT_ADAPTER.validate_python(payload)


class ServerEventModel(BaseModel):
    """Base rules for events created by the backend"""

    model_config = ConfigDict(
        # Server events may contain only explicitly declared fields
        extra="forbid",

        # Prevent accidental modification after the event is created
        frozen=True,

        # Require exact field types in backend code
        strict=True,
    )


class ChatAuthor(ServerEventModel):
    """Public author identity created from verified authentication"""

    # User identifiers must be positive database values
    id: int = Field(gt=0)

    # Username displayed next to the chat message
    username: str = Field(
        min_length=1,
        max_length=USERNAME_MAX_LENGTH,
    )


class AuthenticatedServerEvent(ServerEventModel):
    """Confirmation that WebSocket authentication succeeded"""

    # The default value avoids repeating the event type during construction
    type: Literal["authenticated"] = "authenticated"

    # The backend creates this identity from verified user data
    user: ChatAuthor

class PresenceServerEvent(ServerEventModel):
    """Current unique authenticated users connected to this worker"""

    type: Literal["presence"] = "presence"

    # Each authenticated user appears only once in the presence list
    users: list[ChatAuthor]

class ChatUserJoinedServerEvent(ServerEventModel):
    """Notify chat clients that a user became present"""

    type: Literal["chat_user_joined"] = "chat_user_joined"

    # Generated by the backend so notifications can be safely deduplicated
    event_id: UUID

    # Derived from the authenticated socket and never from client input
    user: ChatAuthor


class ChatUserLeftServerEvent(ServerEventModel):
    """Notify chat clients that a user stopped being present"""

    type: Literal["chat_user_left"] = "chat_user_left"

    # Generated by the backend so notifications can be safely deduplicated
    event_id: UUID

    # Derived from the authenticated socket and never from client input
    user: ChatAuthor

class FriendsChangedServerEvent(ServerEventModel):
    """Notify an authenticated client that its friends data changed"""

    type: Literal["friends_changed"] = "friends_changed"

class ActiveGameChangedServerEvent(ServerEventModel):
    """Notify an authenticated client that its active game data changed"""

    type: Literal["active_game_changed"] = "active_game_changed"

class ChatMessageServerEvent(ServerEventModel):
    """Server confirmed message prepared for broadcasting"""

    type: Literal["chat_message"] = "chat_message"

    # Generated by the backend for this real time message
    # It does not mean that the message is stored in the database
    message_id: UUID

    # Derived from verified authentication and never from client input
    author: ChatAuthor

    # Validated and normalized message content
    text: str = Field(
        min_length=1,
        max_length=CHAT_MESSAGE_MAX_LENGTH,
    )

    # Generated by the backend so the client cannot manipulate message time
    sent_at: datetime


# Stable error codes that may be handled by the frontend
# They describe expected protocol errors without exposing backend internals
ChatErrorCode = Literal[
    "AUTH_REQUIRED",
    "AUTH_INVALID",
    "AUTH_EXPIRED",
    "INVALID_JSON",
    "INVALID_EVENT",
    "EMPTY_MESSAGE",
    "MESSAGE_TOO_LONG",
    "RATE_LIMITED",
    "INTERNAL_ERROR",
]


class ErrorServerEvent(ServerEventModel):
    """Safe error event that may be sent to the frontend"""

    type: Literal["error"] = "error"

    # Stable machine readable code used by frontend logic
    code: ChatErrorCode

    # Short user safe description without stack traces or secret values
    message: str = Field(
        min_length=1,
        max_length=ERROR_MESSAGE_MAX_LENGTH,
    )


# This union contains every event currently produced by the chat backend
ServerEvent = (
    AuthenticatedServerEvent
    | PresenceServerEvent
    | ChatUserJoinedServerEvent
    | ChatUserLeftServerEvent
    | FriendsChangedServerEvent
    | ActiveGameChangedServerEvent
    | ChatMessageServerEvent
    | ErrorServerEvent
)