# Generated by Django 4.2.30 on 2026-08-28 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_bio_alter_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bot_difficulty',
        ),
    ]
