# Generated by Django 4.2.30 on 2026-09-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_bot_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme_color',
        ),
    ]
